# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: query.sql
import datetime
import pydantic
from typing import cast

import sqlalchemy
import sqlalchemy.orm

from python import models


CREATE_EVENT = """-- name: create_event \\:one
INSERT INTO events (name, created_at, updated_at, event_date)
VALUES (:p1, :p2, :p3, :p4)
RETURNING id, name, created_at, updated_at, event_date
"""


GET_EVENT = """-- name: get_event \\:one
SELECT id, name, created_at, updated_at, event_date FROM events WHERE id = :p1
"""


class Querier[T: sqlalchemy.engine.Connection | sqlalchemy.orm.Session]:
    _conn: T

    def __init__(self, conn: T):
        self._conn = conn

    def create_event(self, *, name: str, created_at: pydantic.AwareDatetime, updated_at: pydantic.AwareDatetime | None, event_date: datetime.datetime | None) -> models.Event | None:
        row = self._conn.execute(sqlalchemy.text(CREATE_EVENT), {
            "p1": name,
            "p2": created_at,
            "p3": updated_at,
            "p4": event_date,
        }).first()
        if row is None:
            return None
        return models.Event(
            id=cast(int, row[0]),
            name=cast(str, row[1]),
            created_at=cast(pydantic.AwareDatetime, row[2]),
            updated_at=cast(pydantic.AwareDatetime | None, row[3]),
            event_date=cast(datetime.datetime | None, row[4]),
        )

    def get_event(self, *, id: int) -> models.Event | None:
        row = self._conn.execute(sqlalchemy.text(GET_EVENT), {"p1": id}).first()
        if row is None:
            return None
        return models.Event(
            id=cast(int, row[0]),
            name=cast(str, row[1]),
            created_at=cast(pydantic.AwareDatetime, row[2]),
            updated_at=cast(pydantic.AwareDatetime | None, row[3]),
            event_date=cast(datetime.datetime | None, row[4]),
        )
